spring.application.name=eazystore

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n



spring.datasource.url=jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


spring.jpa.show-sql=${JPA_SHOW_URL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

management.endpoints.web.exposure.include=*

management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Backend Project for Eazy Store E-commerce Applicatio
info.app.version=1.0.0
info.app.contact.email=eazystore@gmail.com

stripe.apiKey=${STRIPE_API_KEY:sk_test_51SkGV4QNFtnpGZwyKrvo9St6KUy8SpcAqQfkWUryPcCC6zvfbKJKGhWR62TdfFPN1y9jXQ0ogaQd881DnodJx9fN00vq7PtU1L}
spring.profiles.active=local

#spring.security.user.name=${EAZYSTORE_USERNAME:likith}
#spring.security.user.password=${EAZYSTORE_PASSWORD:eazystore}
#spring.security.user.roles=${EAZYSTORE_ROLES:USER, ADMIN}


